In [156]:
import json
import pandas as pd

In [157]:
df1=pd.read_json(r"C:\Users\nice\Desktop\Puresoft\Pures_Soft-Recommendation-System\Data\products\orginal\unique_products.json")
df2=pd.read_json(r"C:\Users\nice\Desktop\Puresoft\Pures_Soft-Recommendation-System\Data\products\orginal\unique_products2.json")

In [158]:
product=pd.concat([df1, df2], ignore_index=True)

In [159]:
product

,content,metadata
0,ACM سيكاستيم كريم معالج للبشرة التالفة و تهييج...,"{'product_id': '3760095250540', 'category': 'ك..."
1,ACM كريم SPF50+ للبشرة الجافة عرض 1+1 @,"{'product_id': '', 'category': 'كريم بشرة', 's..."
2,,"{'product_id': '3760095250519', 'category': 'ك..."
3,DC برفان اماراتى حريمى انواع 100 مل,"{'product_id': '6291012875807', 'category': 'ب..."
4,,"{'product_id': '', 'category': 'مانيكير', 'sto..."
...,...,...
12473,يوليشيوس ماء ميسلار 400 مل #,"{'product_id': '6224003272378', 'category': 'م..."
12474,يونو مناديل مبللة 72 بمبى,"{'product_id': '6225000300859', 'category': 'م..."
12475,يونو مناديل مبللة الوان اطفال 120,"{'product_id': '6224009893621', 'category': 'م..."
12476,يوويل بلس لقياس الاكسجين فى الدم,"{'product_id': '6933257922976', 'category': 'ا..."
12477,يوويل جهاز ضغظ ديجيتال شور,"{'product_id': '6933257913004', 'category': 'ا..."

In [160]:
print(product["content"].duplicated().sum())

5392

In [161]:
product['product_id']=product['metadata'].apply(lambda x: x.get('product_id') if isinstance(x, dict) else None)
product.drop_duplicates(subset=['product_id',"content"], inplace=True)

In [162]:
len(product)

7135

In [163]:
product.head()

,content,metadata,product_id
0,ACM سيكاستيم كريم معالج للبشرة التالفة و تهييج...,"{'product_id': '3760095250540', 'category': 'ك...",3760095250540
1,ACM كريم SPF50+ للبشرة الجافة عرض 1+1 @,"{'product_id': '', 'category': 'كريم بشرة', 's...",
2,,"{'product_id': '3760095250519', 'category': 'ك...",3760095250519
3,DC برفان اماراتى حريمى انواع 100 مل,"{'product_id': '6291012875807', 'category': 'ب...",6291012875807
4,,"{'product_id': '', 'category': 'مانيكير', 'sto...",

In [164]:
miss_id = product[product["product_id"].isna()|(product["product_id"] == "")]
miss_id.duplicated(subset=["content"]).sum()

0

In [166]:
product["content"][2]

''

In [167]:
empty=content=product.loc[product["content"].str.strip()==""]
len(empty)

49

In [168]:
product=product[product['content'].str.strip() !='']

In [169]:
product

,content,metadata,product_id
0,ACM سيكاستيم كريم معالج للبشرة التالفة و تهييج...,"{'product_id': '3760095250540', 'category': 'ك...",3760095250540
1,ACM كريم SPF50+ للبشرة الجافة عرض 1+1 @,"{'product_id': '', 'category': 'كريم بشرة', 's...",
3,DC برفان اماراتى حريمى انواع 100 مل,"{'product_id': '6291012875807', 'category': 'ب...",6291012875807
5,M.N اى لينر اسود,"{'product_id': '6923859205119', 'category': 'ا...",6923859205119
6,M.N اى لينر سائل,"{'product_id': '6923859203016', 'category': 'ا...",6923859203016
...,...,...,...
12473,يوليشيوس ماء ميسلار 400 مل #,"{'product_id': '6224003272378', 'category': 'م...",6224003272378
12474,يونو مناديل مبللة 72 بمبى,"{'product_id': '6225000300859', 'category': 'م...",6225000300859
12475,يونو مناديل مبللة الوان اطفال 120,"{'product_id': '6224009893621', 'category': 'م...",6224009893621
12476,يوويل بلس لقياس الاكسجين فى الدم,"{'product_id': '6933257922976', 'category': 'ا...",6933257922976
12477,يوويل جهاز ضغظ ديجيتال شور,"{'product_id': '6933257913004', 'category': 'ا...",6933257913004

In [170]:
product["content"].head(20)

0     ACM سيكاستيم كريم معالج للبشرة التالفة و تهييج...
1               ACM كريم SPF50+ للبشرة الجافة عرض 1+1 @
3                   DC برفان اماراتى حريمى انواع 100 مل
5                                      M.N اى لينر اسود
6                                      M.N اى لينر سائل
7                                       M.N اى لينر فضى
8                                M.N اى لينر قلم دينامك
9                                      M.N ديبلينر اسود
11                      M.N قلم روج خشب الوان + براية $
12                                     M.N قلم كحل ابيض
13                           M.N قلم كحل مشط بنى 1 قطعة
14                                     M.N مسكرة بلاك $
15                                M.N مسكرة حواجب 422 #
16                                 M.N مصحح حواجب 3 لون
17                                 M.N مصحح حواجب 4 لون
18                              M.N هايليتر 4 لون 678 #
19                       NMS سيلك بلاستر 1.25 سم 1 قطعة
20                           NMS سيلك بلاستر 10 سم احمر
21                          NMS سيلك بلاستر 2 سم 1 قطعة
22                        NMS سيلك بلاستر 2.5 سم ازرق #
Name: content, dtype: str

In [171]:
product["content"]=product["content"].str.replace("#"," ")
product["content"]=product["content"].str.replace("@"," ")
product["content"]=product["content"].str.replace("$"," ")
product["content"]=product["content"].str.strip()

In [172]:
len(product)

7086

In [173]:
product["content"].head(20)

0     ACM سيكاستيم كريم معالج للبشرة التالفة و تهييج...
1                 ACM كريم SPF50+ للبشرة الجافة عرض 1+1
3                   DC برفان اماراتى حريمى انواع 100 مل
5                                      M.N اى لينر اسود
6                                      M.N اى لينر سائل
7                                       M.N اى لينر فضى
8                                M.N اى لينر قلم دينامك
9                                      M.N ديبلينر اسود
11                        M.N قلم روج خشب الوان + براية
12                                     M.N قلم كحل ابيض
13                           M.N قلم كحل مشط بنى 1 قطعة
14                                       M.N مسكرة بلاك
15                                  M.N مسكرة حواجب 422
16                                 M.N مصحح حواجب 3 لون
17                                 M.N مصحح حواجب 4 لون
18                                M.N هايليتر 4 لون 678
19                       NMS سيلك بلاستر 1.25 سم 1 قطعة
20                           NMS سيلك بلاستر 10 سم احمر
21                          NMS سيلك بلاستر 2 سم 1 قطعة
22                          NMS سيلك بلاستر 2.5 سم ازرق
Name: content, dtype: str

In [174]:
product.isna().sum()

content       0
metadata      0
product_id    0
dtype: int64

In [175]:
product["metadata"][0]["product_id"]

'3760095250540'

In [176]:
product

,content,metadata,product_id
0,ACM سيكاستيم كريم معالج للبشرة التالفة و تهييج...,"{'product_id': '3760095250540', 'category': 'ك...",3760095250540
1,ACM كريم SPF50+ للبشرة الجافة عرض 1+1,"{'product_id': '', 'category': 'كريم بشرة', 's...",
3,DC برفان اماراتى حريمى انواع 100 مل,"{'product_id': '6291012875807', 'category': 'ب...",6291012875807
5,M.N اى لينر اسود,"{'product_id': '6923859205119', 'category': 'ا...",6923859205119
6,M.N اى لينر سائل,"{'product_id': '6923859203016', 'category': 'ا...",6923859203016
...,...,...,...
12473,يوليشيوس ماء ميسلار 400 مل,"{'product_id': '6224003272378', 'category': 'م...",6224003272378
12474,يونو مناديل مبللة 72 بمبى,"{'product_id': '6225000300859', 'category': 'م...",6225000300859
12475,يونو مناديل مبللة الوان اطفال 120,"{'product_id': '6224009893621', 'category': 'م...",6224009893621
12476,يوويل بلس لقياس الاكسجين فى الدم,"{'product_id': '6933257922976', 'category': 'ا...",6933257922976
12477,يوويل جهاز ضغظ ديجيتال شور,"{'product_id': '6933257913004', 'category': 'ا...",6933257913004

In [177]:
product["content"].duplicated().sum()

37

In [178]:
product.to_json(r"C:\Users\nice\Desktop\Puresoft\Pures_Soft-Recommendation-System\Data\products\preprocessing\products2.json", orient="records", force_ascii=False, indent=4)