In [156]:
import pandas as pd 
import json
import numpy as np
import seaborn as sns

In [138]:
df=pd.read_json(r"C:\Users\nice\Desktop\Puresoft\Pures_Soft-Recommendation-System\Data\Users\user_events.json")

In [139]:
df

                                                events
0    [{'user_id': 'ali', 'event_type': 'product_ope...
1    [{'user_id': 'ali', 'event_type': 'product_ope...
2    [{'user_id': 'ali', 'event_type': 'product_ope...
3    [{'user_id': 'ali', 'event_type': 'product_ope...
4    [{'user_id': 'ali', 'event_type': 'product_ope...
..                                                 ...
245  [{'user_id': 'user_002', 'event_type': 'produc...
246  [{'user_id': 'user_002', 'event_type': 'produc...
247  [{'user_id': 'user_003', 'event_type': 'produc...
248  [{'user_id': 'user_003', 'event_type': 'produc...
249  [{'user_id': 'user_003', 'event_type': 'produc...

[250 rows x 1 columns]

In [140]:
df["events"][0]

[{'user_id': 'ali',
  'event_type': 'product_open',
  'timestamp': '2026-02-20T22:11:38.140966',
  'product_link': 'https://afaq-stores.com/product-details/576'}]

In [141]:
df.duplicated().sum()

0

In [142]:
df_expanded = df.explode("events").reset_index(drop=True)
events_df = pd.json_normalize(df_expanded["events"])
final_df = pd.concat([df_expanded.drop(columns=["events"]), events_df], axis=1)

In [143]:
df=final_df

In [144]:
df

,user_id,event_type,timestamp,product_link,duration,score
0,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,NaN,NaN
1,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,NaN,NaN
2,ali,add_to_cart,2026-02-20T22:11:39.649078,https://afaq-stores.com/product-details/576,NaN,NaN
3,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,NaN,NaN
4,ali,add_to_cart,2026-02-20T22:11:39.649078,https://afaq-stores.com/product-details/576,NaN,NaN
...,...,...,...,...,...,...
996,user_003,product_open,2026-02-25T10:26:40.270200,https://afaq-stores.com/product-details/9750,NaN,1.0
997,user_003,buy_click,2026-02-25T10:26:41.675261,https://afaq-stores.com/product-details/9750,NaN,5.0
998,user_003,product_open,2026-02-25T10:26:40.270200,https://afaq-stores.com/product-details/9750,NaN,1.0
999,user_003,buy_click,2026-02-25T10:26:41.675261,https://afaq-stores.com/product-details/9750,NaN,5.0
1000,user_003,product_exit,2026-02-25T10:26:43.715611,https://afaq-stores.com/product-details/9750,3.39,0.0

In [145]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       1001 non-null   str
 1   event_type    1001 non-null   str
 2   timestamp     1001 non-null   str
 3   product_link  1001 non-null   str
 4   duration      290 non-null    float64
 5   score         869 non-null    float64
dtypes: float64(2), str(4)
memory usage: 133.4 KB

In [146]:
df.drop(columns=["score"],inplace=True)

In [147]:
df["duration"]=df["duration"].fillna(0)

In [148]:
df

,user_id,event_type,timestamp,product_link,duration
0,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,0.00
1,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,0.00
2,ali,add_to_cart,2026-02-20T22:11:39.649078,https://afaq-stores.com/product-details/576,0.00
3,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,0.00
4,ali,add_to_cart,2026-02-20T22:11:39.649078,https://afaq-stores.com/product-details/576,0.00
...,...,...,...,...,...
996,user_003,product_open,2026-02-25T10:26:40.270200,https://afaq-stores.com/product-details/9750,0.00
997,user_003,buy_click,2026-02-25T10:26:41.675261,https://afaq-stores.com/product-details/9750,0.00
998,user_003,product_open,2026-02-25T10:26:40.270200,https://afaq-stores.com/product-details/9750,0.00
999,user_003,buy_click,2026-02-25T10:26:41.675261,https://afaq-stores.com/product-details/9750,0.00
1000,user_003,product_exit,2026-02-25T10:26:43.715611,https://afaq-stores.com/product-details/9750,3.39

In [149]:
df["event_type"].unique()

<ArrowStringArray>
['product_open', 'add_to_cart', 'product_exit', 'buy_click']
Length: 4, dtype: str

In [ ]:
event={
    "product_open":1,
    "add_to_cart":3,
    "buy_click":5,
    "product_exit":0
}

In [151]:
df["event_int"]=df["event_type"].map(event)

In [166]:
df["score"]=(df["event_int"]+df["duration"])/5

In [167]:
df

,user_id,event_type,timestamp,product_link,duration,event_int,score
0,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,0.00,1,0.200
1,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,0.00,1,0.200
2,ali,add_to_cart,2026-02-20T22:11:39.649078,https://afaq-stores.com/product-details/576,0.00,3,0.600
3,ali,product_open,2026-02-20T22:11:38.140966,https://afaq-stores.com/product-details/576,0.00,1,0.200
4,ali,add_to_cart,2026-02-20T22:11:39.649078,https://afaq-stores.com/product-details/576,0.00,3,0.600
...,...,...,...,...,...,...,...
996,user_003,product_open,2026-02-25T10:26:40.270200,https://afaq-stores.com/product-details/9750,0.00,1,0.200
997,user_003,buy_click,2026-02-25T10:26:41.675261,https://afaq-stores.com/product-details/9750,0.00,5,1.000
998,user_003,product_open,2026-02-25T10:26:40.270200,https://afaq-stores.com/product-details/9750,0.00,1,0.200
999,user_003,buy_click,2026-02-25T10:26:41.675261,https://afaq-stores.com/product-details/9750,0.00,5,1.000
1000,user_003,product_exit,2026-02-25T10:26:43.715611,https://afaq-stores.com/product-details/9750,3.39,-1,0.478

In [168]:
df["score"].describe()

count    1001.000000
mean        0.581834
std         0.488402
min         0.066000
25%         0.200000
50%         0.436000
75%         1.000000
max         3.662000
Name: score, dtype: float64